# Site settings
title: Olawale Akinseye
header-img: img/home-bg.jpg
email: brainyfarm@gmail.com
copyright_name: Olawale Akinseye
description: "Olawale Akinseye: android, brainyfarm, BrainySoft"
baseurl: ""
url: "http://masterbrainy.com"
twitter_username: brainyfarm
github_username:  brainyfarm
facebook_username:  whisper2bay
email_username:  brainyfarm@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
